In [3]:
import pandas as pd

## sample pandas DataFrame
df = pd.DataFrame({
    'x1': [1, 2, 3], # int64
    'x2': ['a', 'b', 'c'], # object
    'x3': [True, False, False], # boolean
    'x4': [1.0, 2.0, 3.0], # float64
    'x5': [pd.Timestamp('20230101'), pd.Timestamp('20230102'), pd.Timestamp('20230103')] # datetime64
})
print(df)

   x1 x2     x3   x4         x5
0   1  a   True  1.0 2023-01-01
1   2  b  False  2.0 2023-01-02
2   3  c  False  3.0 2023-01-03

In [9]:
df.filter(items=['x1'])

   x1
0   1
1   2
2   3

## Pandas Column

In [11]:
import itc_utils.flight_service as itcfs

readClient = itcfs.get_flight_client()

nb_data_request = {
    'data_name': """BostonHousing.csv""",
    'interaction_properties': {
        #'row_limit': 500,
        'infer_schema': 'true',
        'infer_as_varchar': 'false'
    }
}

flightInfo = itcfs.get_flight_info(readClient, nb_data_request=nb_data_request)

data_df_1 = itcfs.read_pandas_and_concat(readClient, flightInfo, timeout=240)
data_df_1.head(10)

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,False,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,False,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,False,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,False,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,False,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
5,0.02985,0.0,2.18,False,0.458,6.430,58.7,6.0622,3,222,18.7,394.12,5.21,28.7
6,0.08829,12.5,7.87,False,0.524,6.012,66.6,5.5605,5,311,15.2,395.60,12.43,22.9
7,0.14455,12.5,7.87,False,0.524,6.172,96.1,5.9505,5,311,15.2,396.90,19.15,27.1
8,0.21124,12.5,7.87,False,0.524,5.631,100.0,6.0821,5,311,15.2,386.63,29.93,16.5
9,0.17004,12.5,7.87,False,0.524,6.004,85.9,6.5921,5,311,15.2,386.71,17.10,18.9

In [12]:
data_df_1[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax', 'ptratio', 'b', 'lstat']]

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat
0,0.00632,18.0,2.31,False,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98
1,0.02731,0.0,7.07,False,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14
2,0.02729,0.0,7.07,False,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03
3,0.03237,0.0,2.18,False,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94
4,0.06905,0.0,2.18,False,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,False,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67
502,0.04527,0.0,11.93,False,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08
503,0.06076,0.0,11.93,False,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64
504,0.10959,0.0,11.93,False,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48
505,0.04741,0.0,11.93,False,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88

In [13]:
data_df_1[data_df_1.columns.difference(['medv'])]

,age,b,chas,crim,dis,indus,lstat,nox,ptratio,rad,rm,tax,zn
0,65.2,396.90,False,0.00632,4.0900,2.31,4.98,0.538,15.3,1,6.575,296,18.0
1,78.9,396.90,False,0.02731,4.9671,7.07,9.14,0.469,17.8,2,6.421,242,0.0
2,61.1,392.83,False,0.02729,4.9671,7.07,4.03,0.469,17.8,2,7.185,242,0.0
3,45.8,394.63,False,0.03237,6.0622,2.18,2.94,0.458,18.7,3,6.998,222,0.0
4,54.2,396.90,False,0.06905,6.0622,2.18,5.33,0.458,18.7,3,7.147,222,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,69.1,391.99,False,0.06263,2.4786,11.93,9.67,0.573,21.0,1,6.593,273,0.0
502,76.7,396.90,False,0.04527,2.2875,11.93,9.08,0.573,21.0,1,6.120,273,0.0
503,91.0,396.90,False,0.06076,2.1675,11.93,5.64,0.573,21.0,1,6.976,273,0.0
504,89.3,393.45,False,0.10959,2.3889,11.93,6.48,0.573,21.0,1,6.794,273,0.0
505,80.8,396.90,False,0.04741,2.5050,11.93,7.88,0.573,21.0,1,6.030,273,0.0

In [34]:
from ibm_watson_studio_lib import access_project_or_space
wslib = access_project_or_space()
raw_data_1 = wslib.load_data('kr_health_50.xlsx')
df_health = pd.read_excel(raw_data_1)
#여러 시트가 있을 경우 시트명을 직접 입력하여 dataframe화
#df = pd.read_excel("df_test.xlsx", engine = "openpyxl", sheet_name="Sheet1")#
df_health

,기준년도,가입자일련번호,성별코드,연령대코드(5세단위),시도코드,신장(5Cm단위),체중(5Kg 단위),허리둘레,시력(좌),시력(우),...,감마지티피,흡연상태,음주여부,구강검진 수검여부,치아우식증유무,결손치유무,치아마모증유무,제3대구치(사랑니)이상,치석,데이터공개일자
0,2017,1,1,13,46,170,65,91.0,1.0,1.2,...,25,3,0,1,NaN,NaN,NaN,NaN,1.0,20181126
1,2017,2,2,8,41,150,45,73.4,1.2,1.0,...,10,1,0,1,NaN,NaN,NaN,NaN,1.0,20181126
2,2017,3,1,8,45,175,75,94.0,1.0,0.8,...,136,1,0,1,NaN,NaN,NaN,NaN,0.0,20181126
3,2017,4,2,12,11,155,55,67.5,0.9,1.0,...,30,1,1,0,NaN,NaN,NaN,NaN,NaN,20181126
4,2017,5,1,8,41,175,75,93.0,1.5,1.5,...,68,3,0,0,NaN,NaN,NaN,NaN,NaN,20181126
5,2017,6,1,8,11,170,70,84.8,1.2,1.0,...,33,2,1,1,NaN,NaN,NaN,NaN,1.0,20181126
6,2017,7,1,8,48,175,110,111.5,1.0,1.0,...,45,3,1,0,NaN,NaN,NaN,NaN,NaN,20181126
7,2017,8,2,6,26,170,70,78.0,0.8,0.7,...,13,1,0,0,NaN,NaN,NaN,NaN,NaN,20181126
8,2017,9,1,8,41,170,80,93.0,0.7,0.9,...,51,2,0,1,NaN,NaN,NaN,NaN,1.0,20181126
9,2017,10,1,8,11,170,70,86.0,1.0,1.0,...,88,1,1,1,NaN,NaN,NaN,NaN,0.0,20181126
10,2017,11,2,17,47,150,65,97.0,0.6,0.5,...,16,1,0,1,NaN,NaN,NaN,NaN,0.0,20181126
11,2017,12,2,10,43,155,45,65.2,0.2,0.2,...,21,1,0,0,NaN,NaN,NaN,NaN,NaN,20181126
12,2017,13,1,9,48,170,50,65.0,1.2,1.0,...,19,3,0,0,NaN,NaN,NaN,NaN,NaN,20181126
13,2017,14,2,13,45,150,55,86.0,0.4,0.4,...,21,1,0,1,NaN,NaN,NaN,NaN,1.0,20181126
14,2017,15,2,10,27,160,70,87.0,0.8,0.8,...,12,1,0,0,NaN,NaN,NaN,NaN,NaN,20181126
15,2017,16,2,15,27,150,45,69.0,0.6,0.8,...,10,1,0,0,NaN,NaN,NaN,NaN,NaN,20181126
16,2017,17,1,5,48,175,70,79.0,1.2,0.9,...,20,1,0,0,NaN,NaN,NaN,NaN,NaN,20181126
17,2017,18,2,11,41,155,60,77.0,1.0,0.8,...,8,1,0,1,NaN,NaN,NaN,NaN,1.0,20181126
18,2017,19,1,8,30,175,80,88.0,0.8,0.8,...,18,2,1,1,NaN,NaN,NaN,NaN,0.0,20181126
19,2017,20,2,12,47,150,50,80.0,1.2,1.0,...,16,3,1,0,NaN,NaN,NaN,NaN,NaN,20181126
20,2017,21,2,11,46,155,55,80.0,0.5,0.5,...,19,1,0,1,NaN,NaN,NaN,NaN,1.0,20181126
21,2017,22,1,7,27,170,65,83.0,1.5,1.2,...,35,3,1,1,NaN,NaN,NaN,NaN,1.0,20181126
22,2017,23,2,9,11,155,50,77.0,1.5,1.5,...,10,1,0,1,NaN,NaN,NaN,NaN,1.0,20181126
23,2017,24,1,9,41,170,80,88.0,1.2,1.2,...,65,3,1,1,NaN,NaN,NaN,NaN,2.0,20181126
24,2017,25,1,8,29,175,70,82.3,1.2,1.2,...,80,1,1,1,NaN,NaN,NaN,NaN,1.0,20181126
25,2017,26,2,9,11,165,55,66.0,1.0,1.0,...,18,1,1,0,NaN,NaN,NaN,NaN,NaN,20181126
26,2017,27,2,12,27,165,65,76.5,1.2,1.0,...,14,1,0,1,NaN,NaN,NaN,NaN,1.0,20181126
27,2017,28,1,8,41,165,55,74.0,1.2,1.0,...,20,1,0,0,NaN,NaN,NaN,NaN,NaN,20181126
28,2017,29,1,7,26,175,75,76.0,0.3,0.4,...,30,3,0,1,NaN,NaN,NaN,NaN,1.0,20181126
29,2017,30,1,5,46,175,80,84.0,1.0,1.2,...,13,1,1,0,NaN,NaN,NaN,NaN,NaN,20181126
30,2017,31,1,10,36,160,60,84.0,1.0,0.9,...,24,2,0,0,NaN,NaN,NaN,NaN,NaN,20181126
31,2017,32,2,7,28,165,55,78.0,1.2,0.4,...,16,1,0,0,NaN,NaN,NaN,NaN,NaN,20181126
32,2017,33,1,9,48,165,60,81.0,1.5,1.5,...,80,3,1,0,NaN,NaN,NaN,NaN,NaN,20181126
33,2017,34,1,11,41,170,70,87.0,1.0,1.2,...,47,2,1,1,NaN,NaN,NaN,NaN,0.0,20181126
34,2017,35,2,5,44,155,40,70.0,1.5,1.5,...,31,2,1,1,NaN,NaN,NaN,NaN,0.0,20181126
35,2017,36,1,12,41,170,65,84.0,0.8,0.8,...,26,3,1,0,NaN,NaN,NaN,NaN,NaN,20181126
36,2017,37,2,14,11,155,55,72.0,0.9,0.7,...,16,1,0,0,NaN,NaN,NaN,NaN,NaN,20181126
37,2017,38,2,13,11,150,50,73.2,0.9,1.2,...,15,1,0,1,NaN,NaN,NaN,NaN,1.0,20181126
38,2017,39,2,8,27,155,45,66.0,0.9,0.9,...,14,1,0,0,NaN,NaN,NaN,NaN,NaN,20181126
39,2017,40,2,10,42,155,60,88.0,1.0,1.0,...,12,1,0,0,NaN,NaN,NaN,NaN,NaN,20181126
40,2017,41,1,12,46,160,60,83.0,0.5,0.8,...,48,3,1,0,NaN,NaN,NaN,NaN,NaN,20181126
41,2017,42,2,9,27,160,55,66.0,1.0,1.0,...,13,1,1,0,NaN,NaN,NaN,NaN,NaN,20181126
42,2017,43,2,13,11,155,50,72.0,1.0,1.0,...,24,1,0,0,NaN,NaN,NaN,NaN,NaN,20181126
43,2017,44,2,14,11,145,50,76.0,0.7,1.0,...,15,1,0,0,NaN,NaN,NaN,NaN,NaN,20181126
44,2017,45,1,10,41,165,75,87.5,1.0,1.2,...,29,3,0,0,NaN,NaN,NaN,NaN,NaN,20181126
45,2017,46,2,11,47,155,50,76.0,0.8,0.5,...,13,1,0,0,NaN,NaN,NaN,NaN,NaN,20181126
46,2017,47,2,10,41,155,50,70.0,1.2,1.2,...,15,1,0,0,NaN,NaN,NaN,NaN,NaN,20181126
47,2017,48,2,13,31,155,75,90.0,0.9,1.0,...,21,1,0,0,NaN,NaN,NaN,NaN,NaN,20181126
48,2017,49,1,13,27,170,65,86.4,1.0,1.0,...,42,2,1,0,NaN,NaN,NaN,NaN,NaN,20181126
49,2017,50,1,12,44,170,70,93.0,1.5,1.2,...,25,2,1,0,NaN,NaN,NaN,NaN,NaN,20181126

loc 속성을 사용하여 하나의 열을 제외한 모든 항목을 선택합니다

In [35]:
stocks_df = pd.DataFrame({
    'Stock': ["Amazon","Tesla","Facebook","Boeing"],
    'Price(in $)':  [3180,835,267,209],
    'Sector':["Technology","Technology","Technology","Aircraft"]
})

print("Stocks Dataframe:")
print(stocks_df,"\n")

Stocks Dataframe:
      Stock  Price(in $)      Sector
0    Amazon         3180  Technology
1     Tesla          835  Technology
2  Facebook          267  Technology
3    Boeing          209    Aircraft

In [36]:
print("Stocks DataFrame excluding Sector Column:")
filtered_df=stocks_df.loc[:,stocks_df.columns!="Sector"]
print(filtered_df,"\n")

Stocks DataFrame excluding Sector Column:
      Stock  Price(in $)
0    Amazon         3180
1     Tesla          835
2  Facebook          267
3    Boeing          209

메서드에서axis = 1을 설정하여drop()메서드를 사용하여 DataFrame에서 지정된 열을 삭제할 수 있습니다.

In [37]:
print("Stocks DataFrame excluding Sector Column:")
filtered_df=stocks_df.drop("Sector",axis=1)
print(filtered_df,"\n")

Stocks DataFrame excluding Sector Column:
      Stock  Price(in $)
0    Amazon         3180
1     Tesla          835
2  Facebook          267
3    Boeing          209

Pandas는difference()메서드를 사용하여 하나의 열을 제외한 모든 항목을 선택합니다

In [38]:
print("Stocks DataFrame excluding Sector Column:")
filtered_df=stocks_df[stocks_df.columns.difference(['Sector'])]
print(filtered_df,"\n")

Stocks DataFrame excluding Sector Column:
   Price(in $)     Stock
0         3180    Amazon
1          835     Tesla
2          267  Facebook
3          209    Boeing

Pandas에서 주어진 순서에 대한reindex열

In [39]:
import pandas as pd
df = pd.DataFrame({'a':['1','2','3','4'], 
                   'b': [16,7,6,16],
                   'c':[61,57,16,36],
                   'd':['12','22','13','44'],
                   'e':['Green','Red','Blue','Yellow'],
                   'f':[1,11,23,66]})
print(df)
print('Rearranging ..................')
print('..............................')
df = df.reindex(columns=['a','f','d','b','c','e'])
print(df)

   a   b   c   d       e   f
0  1  16  61  12   Green   1
1  2   7  57  22     Red  11
2  3   6  16  13    Blue  23
3  4  16  36  44  Yellow  66
Rearranging ..................
..............................
   a   f   d   b   c       e
0  1   1  12  16  61   Green
1  2  11  22   7  57     Red
2  3  23  13   6  16    Blue
3  4  66  44  16  36  Yellow

In [40]:
for column in df :
    print(column)

a
f
d
b
c
e

In [41]:
list(df)

['a', 'f', 'd', 'b', 'c', 'e']

In [45]:
list(df.columns)

['a', 'f', 'd', 'b', 'c', 'e']

In [46]:
df.columns.tolist()

['a', 'f', 'd', 'b', 'c', 'e']

In [47]:
list(df.columns.values)

['a', 'f', 'd', 'b', 'c', 'e']

In [49]:
df.columns.values.tolist()

['a', 'f', 'd', 'b', 'c', 'e']